#!/usr/bin/env bash

set -uo pipefail

USER_AGENT='Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0'
RETRY=1
RETRY_DELAY=10
TIMEOUT=3 # seconds

URL_REGEX='https?://[^][{} "`<>),*$|\\]*[^][{} "`<>),*$|\\.:'"'"']'
EXCLUDED_URLS="https?://(\
localhost|\
[0-9]+|\
.+:[0-9]+|\
old.nabble.com|\
news.gmane.org|\
registry.npmjs.org|\
[^/]+.example|\
acme|\
anyhost|\
application|\
example|\
foo|\
host|\
link|\
myhost|\
myusername|\
nohost|\
somehost|\
testuser|\
apache.org/xml|\
www.apache.org/xml|\
java.sun.com/xml|\
java.sun.com/notes|\
java.sun.com/j2ee/dtds|\
maven.apache.org/changes/1.0.0|\
maven.apache.org/POM/4.0.0|\
javax.xml.XMLConstants)"

# https://www.shellhacks.com/bash-colors/
LIGHT_GREEN='\033[1;32m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NO_COLOR='\033[0m'

# --compressed : https://github.com/github/docs/issues/17358
function doCurl() {
  curl -o /dev/null --silent --compressed --connect-timeout "$TIMEOUT" --retry $RETRY --retry-delay $RETRY_DELAY --user-agent "$USER_AGENT" --location --write-out '%{http_code}' "$1"
}

[ ! -d "$1" ] && echo "'$1'  is not a directory" && exit 1

URLS_AND_FILES=$(grep -RioE --exclude-dir={.git,.idea,target,output} --exclude=*.{class,svg} "$URL_REGEX" .)

# Links are processed in a random order to reduce the risk of being blacklisted and temporarily blocked
for url in $(echo "$URLS_AND_FILES" | cut -d ':' -f 2- | sort | uniq | sort -R); do
  if [[ "$url" =~ $EXCLUDED_URLS ]]; then
    echo -e "${LIGHT_GREEN}$url (IGNORED)${NO_COLOR}"

  else
    # we could use --head, but it is not always supported...
    status=$(doCurl "$url")

    if [ "$status" = "200" ]; then
      if [[ $url =~ "http://" ]]; then
        https_status=$(doCurl "${url/http:\/\//https:\/\/}")

        if [ "$https_status" = "200" ]; then
          echo -e "${BLUE}$url ($status) ${GREEN}(HTTPS link available)${NO_COLOR}"
        else
          echo -e "${BLUE}$url ($status) ${RED}(HTTPS link unavailable)${NO_COLOR}"
        fi
      else
        echo -e "${GREEN}$url ($status)${NO_COLOR}"
      fi
    else
      echo -e "${RED}$url ($status)${NO_COLOR}"
    fi
  fi
done
